name: Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv and python-dotenv
        run: |
          pip install uv
          pip install python-dotenv

      - name: Create virtual environment
        run: uv venv

      - name: Install project in editable mode
        run: uv pip install -e .

      - name: Install dependencies from pyproject.toml
        run: uv sync

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DATASET_URL=${{ secrets.DATASET_URL }}" >> .env
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env
          echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> .env

      - name: Data Ingestion
        run: uv run python main.py

  post:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Notify success
        if: success()
        run: |
          echo "âœ… Training Pipeline completed successfully!"
          echo "ğŸš€ Triggering deployment job..."

      - name: Notify failure
        if: failure()
        run: echo "âŒ Pipeline failed. Check logs."
